
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_COMO = 4;
  public static final int T_INGRESAR = 2;
  public static final int T_CON_VALOR = 8;
  public static final int T_ID = 3;
  public static final int EOF = 0;
  public static final int T_CADENA = 7;
  public static final int error = 1;
  public static final int T_PTCOMA = 9;
  public static final int T_STRING = 5;
  public static final int T_ENTERO = 10;
  public static final int T_INT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_INGRESAR",
  "T_ID",
  "T_COMO",
  "T_STRING",
  "T_INT",
  "T_CADENA",
  "T_CON_VALOR",
  "T_PTCOMA",
  "T_ENTERO"
  };
}

